engines:

  phpmd:
    enabled: true
    checks:
      Design/TooManyPublicMethods:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
