
os: "linux"
dist: "trusty"
group: "stable"
language: "php"
php:
  - '5.6'
  - '7.1'
  - '7.2'

addons:
  apt:
    update: true

install: composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
