# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2


defaults: &defaults
  working_directory: ~/eidng8/php-country

  steps:
    - checkout

    - attach_workspace:
        at: ~/eidng8/php-country/tmp

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n --prefer-dist --no-progress

    - save_cache:
        paths:
          - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    # install deps
    - run: sudo apt-get update
    - run: sudo apt-get install -y zlib1g-dev libicu-dev g++
    - run: sudo docker-php-ext-configure intl
    - run: sudo docker-php-ext-install intl
    # run tests!
    - run: sudo mkdir -p ./phpunit/$CIRCLE_JOB
    - run: sudo ./vendor/bin/phpunit --log-junit ./phpunit/$CIRCLE_JOB/junit.xml --coverage-clover ./phpunit/$CIRCLE_JOB/clover.xml --coverage-html ./phpunit/$CIRCLE_JOB/
    - run: sudo ./tmp/cc-test-reporter format-coverage -t clover -o ./tmp/codeclimate.$CIRCLE_JOB.json ./phpunit/$CIRCLE_JOB/clover.xml

    - persist_to_workspace:
        root: tmp
        paths:
          - '*.json'

    - store_artifacts:
        path: ./phpunit/


codeclimate: &codeclimate
  docker:
    - image: circleci/php:5.6.36-cli-node-browsers


jobs:
  code-climate-download:
    <<: *codeclimate
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            sudo mkdir -p ./tmp/
            sudo curl -sSL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./tmp/cc-test-reporter
            sudo chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  code-climate-report:
    <<: *codeclimate
    steps:
      - attach_workspace:
          at: ~/eidng8/php-country/tmp

      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage ./tmp/codeclimate.*.json -p 3 -o ./tmp/coverage.total.json
            ./tmp/cc-test-reporter upload-coverage -i ./tmp/coverage.total.json



  # PHP 5.6
  build-5.6:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6.36-cli-node-browsers


  # PHP 7.1
  build-7.1:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.17-cli-node-browsers



  # PHP 7.2
  build-7.2:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2.5-cli-node-browsers


workflows:
  version: 2
  build:
    jobs:
      - code-climate-download
      - build-5.6:
          requires:
            - code-climate-download
      - build-7.1:
          requires:
            - code-climate-download
      - build-7.2:
          requires:
            - code-climate-download
      - code-climate-report:
          requires:
            - build-5.6
            - build-7.1
            - build-7.2
