# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  # PHP 5.6
  build-5.6:
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6.36-cli-node-browsers

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist --no-progress

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: php -m
      - run: sudo apt-get update
      - run: sudo apt-get install -y zlib1g-dev libicu-dev g++
      - run: sudo docker-php-ext-configure intl
      - run: sudo docker-php-ext-install intl
      - run: ./vendor/bin/phpunit



  # PHP 7.1
  build-7.1:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.17-cli-node-browsers

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist --no-progress

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: php -m
      - run: sudo docker-php-ext-install intl
      - run: ./vendor/bin/phpunit



  # PHP 7.2
  build-7.2:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2.5-cli-node-browsers

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist --no-progress

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: php -m
      - run: sudo docker-php-ext-install intl
      - run: ./vendor/bin/phpunit


workflows:
  version: 2
  build:
    jobs:
      - build-5.6
      - build-7.1
      - build-7.2
